[package]
name = "find_log_processtime"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4"
regex = "1"
indicatif = "0.17.11"
clap = { version = "4.5.30", features = ["derive"] }
anyhow = "1.0.95"
